# Generated by Django 5.1.2 on 2024-10-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('address', models.CharField(max_length=50, unique=True, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=8, verbose_name='Price')),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
